SAMPLING_RATE = 250.0  # Hz
LOW_BANDPASS = 40.0  # Hz
HIGH_BANDPASS = 4.0  # Hz

LOW_FREQ = HIGH_BANDPASS
HIGH_FREQ = LOW_BANDPASS

WINDOW_LEN = 1.0  # seconds
EPOCHS_WINDOW_LEN = WINDOW_LEN  # seconds

BASELINE_LABEL = 5
BREAK_LABEL = 4

HEADSET_CHANNELS = ['Fz', 'C3', 'Cz', 'C4', 'Pz', 'PO7', 'Oz', 'PO8']
